# -*- coding: utf-8 -*-
"""SpeechAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbkI-MygeZc3u3wnV9ELbaJ_CLgr_8vv

# 🎤 SpeechAI – Voice Enabled AI Assistant using Gemma 2B

## 📌 Introduction

SpeechAI is an interactive AI-powered voice assistant that combines **Natural Language Processing (NLP)** and **Speech Processing** to deliver responses in both **text and audio formats**. This project leverages the **Google Gemma 2B** language model from Hugging Face to generate intelligent responses and integrates speech recognition and text-to-speech capabilities for a seamless conversational experience.

The system allows users to either **type their queries or speak through a microphone**, making it flexible and user-friendly. The assistant processes the input, generates a meaningful response using a Large Language Model (LLM), and converts the response into speech output.

---

## 🚀 Key Features

- 🧠 Powered by **Google Gemma 2B** (LLM)
- 🎙️ Accepts both **text and voice input**
- 🔊 Converts AI responses into **realistic speech (gTTS)**
- ⚡ Supports **GPU acceleration (CUDA)** for faster inference
- 🌐 Simple and interactive UI built with **Gradio**
- 🔄 End-to-end pipeline: Speech → Text → AI → Speech

---

## 🛠️ Technologies Used

- **Transformers (Hugging Face)** – For loading and running the Gemma 2B model  
- **PyTorch** – Backend framework for model execution  
- **Gradio** – For building the web-based interface  
- **SpeechRecognition** – Converts voice input into text  
- **gTTS (Google Text-to-Speech)** – Converts text responses into audio  

---

## ⚙️ How It Works

1. User provides input (text or voice)
2. If voice is given → converted to text using SpeechRecognition
3. Text input is tokenized and passed to the **Gemma 2B model**
4. Model generates a response using NLP
5. Response is converted into speech using gTTS
6. Output is displayed as:
   - 📝 Text response
   - 🔊 Audio playback

---

## 📎 Conclusion

SpeechAI showcases the power of combining **LLMs + Speech AI + Web UI** into a single application. It serves as a strong foundation for building real-world AI assistants and conversational systems.
"""

pip install gradio transformers gtts playsound speechrecognition

import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer
from gtts import gTTS
import os
import speech_recognition as sr
import torch

from huggingface_hub import login

login("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")

# Load model and tokenizer

model_name = "google/gemma-2b"
# Name of the pretrained LLM from Hugging Face (LLaMA 2 chat model)

# Check if CUDA (GPU) is available and move model to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# If GPU is available → use it, otherwise use CPU

print(f"Using device: {device}")
# Prints whether GPU or CPU is being used

# Load model and tokenizer with token
model = AutoModelForCausalLM.from_pretrained(
    model_name
).to(device)
# Loads the language model and moves it to GPU/CPU

tokenizer = AutoTokenizer.from_pretrained(
    model_name
)
# Loads tokenizer (converts text ↔ tokens)

# Function to generate chatbot response without chat history
def chatbot_response(user_input):

    # Convert user text into tokens (numbers) for model
    inputs = tokenizer(
        user_input,
        return_tensors="pt",   # return PyTorch tensors
        max_length=512,        # limit input length
        truncation=True        # cut if too long
    ).to(device)              # move to GPU/CPU

    # Generate response from model
    outputs = model.generate(**inputs)

    # Convert tokens back to readable text
    bot_reply = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Remove repeated input from output (common issue in LLMs)
    if bot_reply.startswith(user_input):
        bot_reply = bot_reply[len(user_input):].strip()

    return bot_reply

def text_to_audio(response, voice="default"):

    # Convert text response into speech using gTTS (Google Text-to-Speech)
    tts = gTTS(text=response, lang="en", slow=False)

    # File path where audio will be saved
    audio_path = "response.mp3"

    # Save the generated speech to file
    tts.save(audio_path)

    return audio_path

def process_input(text_input, voice_input):

    # If voice input is provided, convert it to text
    if voice_input:
        recognizer = sr.Recognizer()

        with sr.AudioFile(voice_input) as source:
            audio = recognizer.record(source)

        try:
            text_input = recognizer.recognize_google(audio)

        except sr.UnknownValueError:
            return "Sorry, I did not understand that.", None

        except sr.RequestError:
            return "Speech service error.", None

    # Handle empty input
    if not text_input:
        return "Please provide input.", None

    # Generate AI response
    response = chatbot_response(text_input)

    # Convert response to audio (FIXED)
    audio_file = text_to_audio(response)

    return response, audio_file

with gr.Blocks() as voice_assistant:

    gr.Markdown("""
    #  AI Voice Assistant
    Type or speak your query and get response in text + audio
    """)

    with gr.Row():

        with gr.Column():
            text_input = gr.Textbox(label="Enter your message")
            voice_input = gr.Audio(type="filepath", label="Record your voice")
            submit_btn = gr.Button("Submit")

        with gr.Column():
            response_output = gr.Textbox(label="AI Response")
            audio_output = gr.Audio(label="Audio Response")

    submit_btn.click(
        fn=process_input,
        inputs=[text_input, voice_input],
        outputs=[response_output, audio_output]
    )

#  Launch app
voice_assistant.launch(share = True)

